Weights:
  depthanything3:
    DA3: './weights/depthanything/model.safetensors'
    DA3_CONFIG: './weights/depthanything/config.json'
    SALAD: './weights/depthanything/dino_salad.ckpt'
  mapanything:
    MAP: './weights/mapanything/model.safetensors'
    MAP_CONFIG: './weights/mapanything/config.json'
  sam3d:
    SAM3D: './weights/sam3d'
    SAM3D_CONFIG: './weights/sam3d'
  pi3:
    PI3: './weights/pi3/model.safetensors'
    PI3_CONFIG: './weights/pi3/config.json'
  vggt:
    VGGT: './weights/vggt/model.pt'

