RunArgs:
  area_path: ./dataset/UrbanScene/PolyTech
  block_name: ""
  config_path: ./configs/base_config.yaml
  output_path: ./exp/urban/run_urbanscene_mapanything_PolyTech
  model_name: mapanything
  chunk_size: 60
  overlap: 24
  max_chunks: -1
  anchor_cam_index: -1
  num_cameras_to_use: 1
  camera_ids: []
  da3_infer_mode: global_chunk
  da3_stable_fusion: 1
  da3_group_frames: 8
  da3_group_overlap: 2
  device: cuda

