GlobalMerge:
  base_output_dir: './exp/matrixcity'
  city_size: 'big_city'
  split: 'train'
  model_name: 'depthanything3'
  output_path: ''
  config_path: './configs/base_config.yaml'
  use_icp_fallback: 1
  max_chunks_per_block: -1

  SALAD:
    sample_stride: 10
    similarity_threshold: 0.80
    min_match_count: 3

  ICP:
    voxel_size: 0.5
    max_iter: 100
    max_correspondence_distance_factor: 5
    fitness_threshold: 0.05
    max_points_per_block: 500000
    conf_threshold_ratio: 0.75

  Pointcloud_Save:
    sample_ratio: 0.015
    conf_threshold_coef: 0.75
